#!/bin/bash

curl \
  -v \
  -X DELETE \
  "https://api.cloudflare.com/client/v4/zones/01a3f3d8b9e992719ed841e568b349f8/purge_cache" \
  -H "X-Auth-Email: aaron.r.stacy@gmail.com" \
  -H "X-Auth-Key: $CLOUDFLARE_API_KEY" \
  -H "Content-Type: application/json" \
  --data '{"purge_everything":true}' \
  2>&1 | grep -v X-Auth-Key
